# ----------------------------------------------
# GENERAL INFO
# ----------------------------------------------

# Author Info
name:           Vitor Britto
description:    Desenvolvedor Web
avatar:         assets/images/avatar.jpg
twitter:        https://twitter.com/vitorbritto
facebook:       https://www.facebook.com/vbwebstudio
github:         https://github.com/vitorbritto
rssfeed:        http://feeds.feedburner.com/vitorbritto

# Web Serve
# fullurl:        'http://0.0.0.0:4000'                  # use this url for DEVELOPMENT
fullurl:        'http://www.vitorbritto.com.br/blog'   # use this url for PRODUCTION


# ----------------------------------------------
# STRUCTURE AND FILES
# ----------------------------------------------

# Exclude directories and/or files
exclude: [
'bower.json',
'package.json',
'Gruntfile.js',
'config.rb',
'.editorconfig',
'.gitignore',
'Rakefile',
'Gemfile',
'Gemfile.lock',
'sass',
'node_modules',
'main.js',
'README.md',
]

# Main Config
source:         .
destination:    ./_build
plugins:        ./_plugins
layouts:        ./_layouts

# Outputing
permalink:      :title/

# Conversion
markdown:       redcarpet
highlighter:    pygments

# Markdown Processors
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'tables',
        'with_toc_data'
    ]
